# Generated by Django 4.2.1 on 2023-05-20 15:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contato", "0002_categoria_contato_data_atualizacao_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contato",
            name="fone",
            field=models.IntegerField(verbose_name="telefone"),
        ),
        migrations.AlterField(
            model_name="contato",
            name="nome",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.MinLengthValidator(3),
                    django.core.validators.MaxLengthValidator(60),
                ],
            ),
        ),
    ]
